(add-to-list 'load-path "~/packages/emacs/xslide")
(require 'xslide)
(add-to-list 'auto-mode-alist '("\\.xsl\\'" . xsl-mode))
;(add-to-list 'load-path "~/packages/emacs/xslt-process/lisp")
;(require 'xslt-process)
